### ISSUE TITLE
Component library

### ISSUE THREAD

**Issue by szekelypeter** [salierri/geltara#17]
Check for available component librarys for the project like material-ui and uikit.
Choose the best one and rewrite the existing frontend with this component (if needed)

**Comment by szekelypeter** [comment]
A lot of liraries wer efound, but checking a few requirements it has been narrowed down to 2:
https://react-bootstrap.github.io/getting-started/introduction/
https://material-ui.com/

**Comment by salierri** [comment]
I cast my vote for material-ui based on the nice default themes and the built-in support for collapsible lists

**Comment by balintkiraly** [comment]
I can recommend the Chakra UI component library.
https://chakra-ui.com/

- Full TypeScript support
- Good documentation
- Good community
- Customizable theme
- It's inspired by Tailwind CSS
- It look pretty good

_Edited:_
- Build-in dark mode :heart_eyes:
